# MomijiHarvester Configuration

# List of lecture codes for small mode (testing/development)
small_lecture_codes:
  - "10000100"
  # Add more lecture codes for small testing if needed

# List of all lecture codes for full mode (production)
# TODO: Implement a way to automatically generate or obtain the full list of lecture codes
full_lecture_codes:
  # - "..."
drop_columns:
  sample:
    - "授業科目名_フリガナ"
    - "担当教員名_フリガナ"
    - "週時間"
    - "英文授業科目名"
    - "授業の方法"
    - "授業の方法_詳細情報"
    - "授業のキーワード"
    - "教科書_参考書等"
    - "授業で使用する_メディア_機器等"
    - "教職専門科目"
    - "教科専門科目"
    - "プログラムの中でのこの授業科目の位置づけ"
    - "詳細情報"
    - "授業で取り入れる_学習手法"
    - "授業計画"
    - "成績評価の基準等"
    - "学問分野_分野"
    - "学問分野_分科"
    - "到達度評価の評価項目"
    - "実務経験"
    - "実務経験の概要と_それに基づく授業内容"
  all:
    - "授業科目名_フリガナ"
    - "担当教員名_フリガナ"
    - "週時間"
    - "英文授業科目名"
    - "授業の方法"
    - "授業の方法_詳細情報"
    - "授業のキーワード"
    - "教科書_参考書等"
    - "授業で使用する_メディア_機器等"
    - "教職専門科目"
    - "教科専門科目"
    - "プログラムの中でのこの授業科目の位置づけ"
    - "詳細情報"
    - "授業で取り入れる_学習手法"
    - "授業計画"
    - "成績評価の基準等"
    - "学問分野_分野"
    - "学問分野_分科"
    - "到達度評価の評価項目"
    - "実務経験"
    - "実務経験の概要と_それに基づく授業内容"
